version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run unit tests
          command: |
            pytest --cov-report term-missing --cov=src/tests/
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            VERSION="1.1.1"

            docker build -t ghcr.io/${CIRCLE_PROJECT_USERNAME}/liberando-productos-sergi-castillo:latest .

            echo "${GHCR_PAT}" | docker login ghcr.io -u ${CIRCLE_PROJECT_USERNAME} --password-stdin

            docker images

            docker push ghcr.io/${CIRCLE_PROJECT_USERNAME}/liberando-productos-sergi-castillo:latest
